### ISSUE TITLE
Any Plans for Multi-GPU Support?

### ISSUE THREAD

**Issue by chenxiaodong2002** [woct0rdho/transformers-qwen3-moe-fused#1]
I've been using this kernel for inference, and it works perfectly on a single GPU. However, when attempting to run it on multiple GPUs, I encountered a CUDA error: "an illegal memory access was encountered." I was wondering if there are any plans to support multi-GPU operation in the future?

**Comment by woct0rdho** [comment]
@takfate I think so. There can be a lot of complicated techniques to do expert parallel and compute-communicate overlap, but I guess model parallel is enough for most people doing fine-tuning.

**Comment by woct0rdho** [comment]
@edgeinfinity1 This seems to be an issue of Unsloth. Anyway, they don't officially support multi-GPU yet.

At this point, I think the main purpose to use Unsloth is for their gradient checkpointing to save VRAM. The biggest speedup is already covered by my fused MoE kernel, and other speedups such as fast LoRA and fast cross entropy are not so significant.

As you have multiple GPUs, I guess you're not so tight in VRAM. You can try to train without Unsloth, similar to my `example_train_tiny.py`

**Comment by woct0rdho** [comment]
@edgeinfinity1 Sorry I missed your edit. I'll receive a notification only if you make a new comment.

Are you using the latest version of the `peft` package? `_register_custom_module` was only added recently.

**Comment by edgeinfinity1** [comment]
> [@edgeinfinity1](https://github.com/edgeinfinity1) Sorry I missed your edit. I'll receive a notification only if you make a new comment.
> 
> Are you using the latest version of the `peft` package? `_register_custom_module` was only added recently.

I'll try it later, sorry for forgetting a mention.
I've been trying to make Megatron work with qwen3-moe these days since they've added LoRA support, but the environment construction is complex with RTX50s. I'll commit here whenever I find some valuable clue.

**Comment by swagdowdlez** [comment]
> I have made finetuning work with Megatron. Works like a charm.
> 
> <img alt="Image" width="685" height="957" src="https://private-user-images.githubusercontent.com/133833590/473787089-fa50d8b3-44bf-4a87-bfbc-94154eb702ff.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUyNjUwMTgsIm5iZiI6MTc1NTI2NDcxOCwicGF0aCI6Ii8xMzM4MzM1OTAvNDczNzg3MDg5LWZhNTBkOGIzLTQ0YmYtNGE4Ny1iZmJjLTk0MTU0ZWI3MDJmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxNVQxMzMxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDlmY2Y4MzVmNDE1ZWExYjZhOTVkYzk1Nzc4NDlkZGYzZjg4MDNiYjdhMmE1OWVmOWNiYmYwODFhOTViYmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xTv8bQJVi69mfzjaKjd85Qb90PMGwBUFzxNuQk0Hblg">
> It has good optimization for MoE, and supports customized model layout (experimental) just like `device_map`. Also has unbelievably high utilization. Except for a little bit of complexity setting up, I would recommend any multi-gpu user to go for Megatron. Because of this and my poor understanding about low-level controlling LLM, I'll stop making more effort on this. Sorry about that but at least I found a good solution for my case.

Can you please tell me how you did it? I've been trying for 2 weeks and made 0 progress so far @edgeinfinity1

**Comment by swagdowdlez** [comment]
> > Can you please tell me how you did it? I've been trying for 2 weeks and made 0 progress so far [@edgeinfinity1](https://github.com/edgeinfinity1)
> 
> You can use https://github.com/modelscope/ms-swift as a wrapping. They provide a pretty detailed document on how to LoRA with megatron. You can do it within a few lines of CLI.

NNODES=$WORLD_SIZE \
NODE_RANK=$RANK \
megatron sft \
    --load Qwen3-30B-A3B-Base-mcore \
    --dataset 'liucong/Chinese-DeepSeek-R1-Distill-data-110k-SFT' \
    --tensor_model_parallel_size 2 \
    --expert_model_parallel_size 8 \
    --moe_grouped_gemm true \
    --moe_shared_expert_overlap true \
    --moe_aux_loss_coeff 0.01 \
    --micro_batch_size 1 \
    --global_batch_size 16 \
    --packing true \
    --recompute_granularity full \
    --recompute_method uniform \
    --recompute_num_layers 1 \
    --train_iters 2000 \
    --eval_iters 50 \
    --finetune true \
    --cross_entropy_loss_fusion true \
    --lr 1e-5 \
    --lr_warmup_iters 100 \
    --min_lr 1e-6 \
    --save megatron_output/Qwen3-30B-A3B-Base \
    --eval_interval 200 \
    --save_interval 200 \
    --max_length 8192 \
    --num_workers 8 \
    --dataset_num_proc 8 \
    --no_save_optim true \
    --no_save_rng true \
    --sequence_parallel true \
    --use_flash_attn true


so I have to run something like this? I found this on this page https://github.com/QwenLM/Qwen3/discussions/1301

**Comment by edgeinfinity1** [comment]
> so I have to run something like this? I found this on this page [QwenLM/Qwen3#1301](https://github.com/QwenLM/Qwen3/discussions/1301)

First install ms-swift package as they explain in the documents, then you can find some examples [here](https://github.com/modelscope/ms-swift/blob/main/examples/train/megatron/lora/qwen3_235b.sh)

**Comment by swagdowdlez** [comment]
> We have implemented multi-GPU training using the **accelerate** library 

Hi! Do you have the python script that you used **accelerate** with for traning? 
Did you use the default SFT trainer then used accelerate to train the LORA with 2 GPUs?

**Comment by woct0rdho** [comment]
Hi @chenxiaodong2002 , the illegal memory access should be fixed in https://github.com/woct0rdho/transformers-qwen3-moe-fused/commit/e83d1eb61a23651c6345ff037714546ae9f616bd

**Comment by woct0rdho** [comment]
@monosabbath Is there any error log?

The inference script is just for testing the correctness, and its speed is expected to be slower than llama.cpp and vLLM. The autotune config is mainly for training. You can see https://github.com/woct0rdho/transformers-qwen3-moe-fused/issues/16 for some issues about the inference script.
